vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        dish:
            uri_prefix: /uploads/images/dish
            upload_destination: '%kernel.project_dir%/public/uploads/images/dish'
            namer: Vich\UploaderBundle\Naming\UniqidNamer